name: BuildMyThing
main: bassintag.buildmything.common.BuildMyThing
version: 1.6
description: >
             Draw something in Minecraft.
commands:
  bmt:
    description: The main command of Build My Thing
permissions:
  bmt.admin:
    description: Allows you to create rooms
    default: op
  bmt.default:
    description: Allows you to play etc...
    default: true